site_name: CodeIgniter AssetConnect
site_description: AssetConnect is a file management library for CodeIgniter 4 that allows you to associate files with any entity in your application.

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/flame.svg
  favicon: assets/favicon.ico
  icon:
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: codeigniter
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.instant
    - content.code.copy
    - navigation.footer
    - content.action.edit
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

extra:
  homepage: https://maniaba.github.io/asset-connect/
  generator: false
  version:
    provider: mike
    default: latest
    alias: true

  social:
    - icon: material/github
      link: https://github.com/maniaba/asset-connect
      name: GitHub
    - icon: material/twitter
      link: https://twitter.com/CodeIgniterPhp
      name: X
    - icon: material/forum
      link: https://forum.codeigniter.com
      name: Forum Codeigniter
    - icon: material/slack
      link: https://join.slack.com/t/codeigniterchat/shared_invite/zt-244xrrslc-l_I69AJSi5y2a2RVN~xIdQ
      name: Slack

site_url: https://maniaba.github.io/asset-connect/
repo_url: https://github.com/maniaba/asset-connect
edit_uri: edit/develop/docs/
copyright: Copyright &copy; 2025 Maniaba.

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false

plugins:
  - search
  - mike:
      alias_type: redirect
      canonical_version: latest

extra_css:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.8.0/build/styles/github.min.css
  - assets/css/codeigniter.css
  - assets/css/codeigniter_dark_mode.css

extra_javascript:
  - https://cdn.jsdelivr.net/gh/highlightjs/cdn-release@11.8.0/build/highlight.min.js
  - assets/js/hljs.js

nav:
  - Home: index.md
  - Installation: installation.md
  - Upgrade:
      - Upgrade from 2.1.0 to 3.0.0: upgrade-3.0.md
      - Upgrade from 2.0.0 to 2.1.0: upgrade-2.1.md
      - Upgrade from 1.0.2 to 2.0.0: upgrade-2.0.md
  - Configuration:
      - Overview: configuration.md
      - Storage: storage.md
      - Custom Asset Collections: custom-asset-collections.md
      - Custom Path Generators: custom-path-generators.md
      - Custom URL Generator: custom-url-generator.md
  - Usage:
      - Basic usage: basic-usage.md
      - Advanced usage: advanced-usage.md
      - Examples: examples.md
  - Assets:
      - Overview: asset.md
      - Asset Adder: asset-adder.md
      - Asset Collections: asset-collections.md
      - Pending Assets:
          - Overview: pending.md
          - Pending Asset Manager: pending-asset-manager.md
          - Custom Pending Storage: custom-pending-storage.md
          - Pending Security Token: pending-security-token.md
  - Events: events.md
  - Validation: validation.md
  - Troubleshooting: troubleshooting.md
  - Module Structure: module-structure.md
